trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy to AWS EC2'
    environment:
      name: 'AWS_EC2'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              # Create web target folders with admin permissions
              sudo mkdir -p /var/www/html/
              
              # Force copy index.html directly into the folder
              sudo cp -f $(Pipeline.Workspace)/s/index.html /var/www/html/
            displayName: 'Deploy index.html to Nginx Web Server'
